// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package akka.example.udp_protobuf.proto;

public interface ContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:akka.example.udp_protobuf.proto.Content)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string body = 1;</code>
   */
  java.lang.String getBody();
  /**
   * <code>string body = 1;</code>
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
