// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package akka.example.udp_protobuf.proto;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_akka_example_udp_protobuf_proto_Content_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_akka_example_udp_protobuf_proto_Content_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_akka_example_udp_protobuf_proto_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_akka_example_udp_protobuf_proto_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\037akka.example.udp_protob" +
      "uf.proto\"\027\n\007Content\022\014\n\004body\030\001 \001(\t\"i\n\007Mes" +
      "sage\022\r\n\005title\030\001 \001(\t\022\023\n\013contentSize\030\002 \001(\005" +
      "\022:\n\010contents\030\003 \003(\0132(.akka.example.udp_pr" +
      "otobuf.proto.ContentB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_akka_example_udp_protobuf_proto_Content_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_akka_example_udp_protobuf_proto_Content_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_akka_example_udp_protobuf_proto_Content_descriptor,
        new java.lang.String[] { "Body", });
    internal_static_akka_example_udp_protobuf_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_akka_example_udp_protobuf_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_akka_example_udp_protobuf_proto_Message_descriptor,
        new java.lang.String[] { "Title", "ContentSize", "Contents", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
