// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package akka.example.udp_protobuf.proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:akka.example.udp_protobuf.proto.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>int32 contentSize = 2;</code>
   */
  int getContentSize();

  /**
   * <code>repeated .akka.example.udp_protobuf.proto.Content contents = 3;</code>
   */
  java.util.List<akka.example.udp_protobuf.proto.Content> 
      getContentsList();
  /**
   * <code>repeated .akka.example.udp_protobuf.proto.Content contents = 3;</code>
   */
  akka.example.udp_protobuf.proto.Content getContents(int index);
  /**
   * <code>repeated .akka.example.udp_protobuf.proto.Content contents = 3;</code>
   */
  int getContentsCount();
  /**
   * <code>repeated .akka.example.udp_protobuf.proto.Content contents = 3;</code>
   */
  java.util.List<? extends akka.example.udp_protobuf.proto.ContentOrBuilder> 
      getContentsOrBuilderList();
  /**
   * <code>repeated .akka.example.udp_protobuf.proto.Content contents = 3;</code>
   */
  akka.example.udp_protobuf.proto.ContentOrBuilder getContentsOrBuilder(
      int index);
}
